######################################################################
# Automatically generated by qmake (3.0) Tue Sep 20 12:53:50 2016
######################################################################

TEMPLATE = app
TARGET = wordchain
INCLUDEPATH += .

# Input
SOURCES += src/wordchain.cpp
SOURCES += res/dictionary.txt
SOURCES += lib/readme.txt
